package com.kata.bank.model;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Objects;

public class AccountOperation {

    private Long id;

    private final String accountId;

    private final AccountOperationType type;

    private final BigDecimal amount;

    private final BigDecimal balance;

    private final LocalDate date;

    public AccountOperation(final Long id, final String accountId, final AccountOperationType type, final BigDecimal amount
            , final BigDecimal balance, final LocalDate date) {
        this.id = id;
        this.accountId = accountId;
        this.type = type;
        this.amount = amount;
        this.balance = balance;
        this.date = date;
    }

    public AccountOperation(final String accountId, final AccountOperationType type, final BigDecimal amount
            , final BigDecimal balance, final LocalDate date) {
        this.accountId = accountId;
        this.type = type;
        this.amount = amount;
        this.balance = balance;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public String getAccountId() {
        return accountId;
    }

    public AccountOperationType getType() {
        return type;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public BigDecimal getBalance() {
        return balance;
    }

    public LocalDate getDate() {
        return date;
    }

    // generated by the IDE
    @Override
    public boolean equals(final Object object) {
        if (this == object) {
            return true;
        }
        if (object == null || getClass() != object.getClass()) {
            return false;
        }
        final var that = (AccountOperation) object;
        return Objects.equals(id, that.id)
                && Objects.equals(accountId, that.accountId)
                && type == that.type
                && Objects.equals(amount, that.amount)
                && Objects.equals(balance, that.balance)
                && Objects.equals(date, that.date);
    }

    // generated by the IDE
    @Override
    public int hashCode() {
        return Objects.hash(id, accountId, type, amount, balance, date);
    }
}
