package com.kata.bank.dto;

import java.math.BigDecimal;
import java.util.Objects;

public class AccountOperationResponseDto {

    private final AccountOperationResultType result;

    private final String message;

    private final BigDecimal balance;

    public AccountOperationResponseDto(final AccountOperationResultType result, final String message, final BigDecimal balance) {
        this.result = result;
        this.message = message;
        this.balance = balance;
    }

    public AccountOperationResultType getResult() {
        return result;
    }

    public String getMessage() {
        return message;
    }

    public BigDecimal getBalance() {
        return balance;
    }

    // generated by the IDE
    @Override
    public boolean equals(Object object) {
        if (this == object) {
            return true;
        }
        if (object == null || getClass() != object.getClass()) {
            return false;
        }
        final var that = (AccountOperationResponseDto) object;
        return result == that.result
                && Objects.equals(message, that.message)
                && Objects.equals(balance, that.balance);
    }

    // generated by the IDE
    @Override
    public int hashCode() {
        return Objects.hash(result, message, balance);
    }
}
