package com.kata.bank.dto;

import com.kata.bank.model.AccountOperationType;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Objects;

public class AccountOperationDto {

    private final AccountOperationType type;

    private final BigDecimal amount;

    private final BigDecimal balance;

    private final LocalDate date;

    public AccountOperationDto(final AccountOperationType type, final BigDecimal amount, final BigDecimal balance, final LocalDate date) {
        this.type = type;
        this.amount = amount;
        this.balance = balance;
        this.date = date;
    }

    public AccountOperationType getType() {
        return type;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public BigDecimal getBalance() {
        return balance;
    }

    public LocalDate getDate() {
        return date;
    }

    // generated by the IDE
    @Override
    public boolean equals(Object object) {
        if (this == object) {
            return true;
        }
        if (object == null || getClass() != object.getClass()) {
            return false;
        }
        final var that = (AccountOperationDto) object;
        return type == that.type
                && Objects.equals(amount, that.amount)
                && Objects.equals(balance, that.balance)
                && Objects.equals(date, that.date);
    }

    // generated by the IDE
    @Override
    public int hashCode() {
        return Objects.hash(type, amount, balance, date);
    }
}
