package com.kata.bank.dto;

import java.util.Collections;
import java.util.List;
import java.util.Objects;

public class AccountOperationsListingDto {

    private final List<AccountOperationDto> operations;

    public AccountOperationsListingDto(List<AccountOperationDto> operations) {
        this.operations = operations;
    }

    public List<AccountOperationDto> getOperations() {
        return Collections.unmodifiableList(operations);
    }

    // generated by the IDE
    @Override
    public boolean equals(Object object) {
        if (this == object) {
            return true;
        }
        if (object == null || getClass() != object.getClass()) {
            return false;
        }
        final var that = (AccountOperationsListingDto) object;
        return Objects.equals(operations, that.operations);
    }

    // generated by the IDE
    @Override
    public int hashCode() {
        return Objects.hash(operations);
    }
}
